// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function CreateSubscription(arg1) {
  return window['go']['main']['App']['CreateSubscription'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function DisableAutostart() {
  return window['go']['main']['App']['DisableAutostart']();
}

export function EnableAutostart() {
  return window['go']['main']['App']['EnableAutostart']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetRunningState() {
  return window['go']['main']['App']['GetRunningState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function ImportSubscription(arg1) {
  return window['go']['main']['App']['ImportSubscription'](arg1);
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadSubscriptions() {
  return window['go']['main']['App']['LoadSubscriptions']();
}

export function OnExit() {
  return window['go']['main']['App']['OnExit']();
}

export function SaveProfiles() {
  return window['go']['main']['App']['SaveProfiles']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSubscriptions() {
  return window['go']['main']['App']['SaveSubscriptions']();
}

export function SetupTray(arg1) {
  return window['go']['main']['App']['SetupTray'](arg1);
}

export function StartVless(arg1) {
  return window['go']['main']['App']['StartVless'](arg1);
}

export function StopVless() {
  return window['go']['main']['App']['StopVless']();
}

export function TcpPing(arg1) {
  return window['go']['main']['App']['TcpPing'](arg1);
}

export function UpdateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}

export function UrlTest(arg1) {
  return window['go']['main']['App']['UrlTest'](arg1);
}
