// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddProfile(arg1:string):Promise<string>;

export function CheckAppUpdate():Promise<main.AppUpdateInfo>;

export function CreateSubscription(arg1:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<Array<main.Profile>>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function DisableAutostart():Promise<void>;

export function EnableAutostart():Promise<void>;

export function GetLogs():Promise<Array<string>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function GetRunningProcesses():Promise<Array<string>>;

export function GetRunningState():Promise<boolean>;

export function GetSettings():Promise<main.Settings>;

export function GetSubscriptions():Promise<Array<main.Subscription>>;

export function ImportSubscription(arg1:string):Promise<string>;

export function LoadProfiles():Promise<Array<main.Profile>>;

export function LoadSettings():Promise<main.Settings>;

export function LoadSubscriptions():Promise<Array<main.Subscription>>;

export function OpenUrl(arg1:string):Promise<void>;

export function SaveProfiles():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<string>;

export function SaveSubscriptions():Promise<void>;

export function SetupTray(arg1:context.Context):Promise<void>;

export function StartVless(arg1:string):Promise<string>;

export function StopVless():Promise<string>;

export function TcpPing(arg1:string):Promise<number>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateSubscription(arg1:string):Promise<string>;

export function UrlTest(arg1:string):Promise<number>;
